export const metadata = {
  title: "My Test Title",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <div>
      <h2>Hello from Next.js</h2>
    </div>
  );
}